FROM node
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
ENV CI=true
ENV WDS_SOCKET_PORT=0
# RUN npm run build
EXPOSE 3000
CMD [ "npm", "run", "dev" , "--ignore-watch" , "\"src/**/*\"" ]
