apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-deployment-label
  template:
    metadata:
      labels:
        app: kafka-deployment-label
    spec:
      containers:
        - name: kafka-container
          image: bitnami/kafka
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://localhost:9092'
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: 'CONTROLLER'
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: '1@127.0.0.1:9093'
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
            - name: KAFKA_CFG_LISTENERS
              value: 'PLAINTEXT://:9092,CONTROLLER://:9093'
            - name: KAFKA_CFG_PROCESS_ROLES
              value: 'broker,controller'
            - name: KAFKA_ENABLE_KRAFT
              value: 'yes'

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka-deployment-label
  type: ClusterIP
  ports:
    - name: kafka-cluster-ip-service-port-name
      protocol: TCP
      port: 9092
      targetPort: 9092
